language: python
python:
  - 2.7
  - pypy
  - 3.3
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]]; then python -m unittest discover -s tests/3/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7* ]]; then python -m unittest discover -s tests/2/; fi
after_success: codecov
install: pip install codecov
